name: fortuna
description: An application of the Hedonist philosophy.
publish_to: 'none'
version: 3.1.0
environment:
  sdk: ">=2.16.0 <3.0.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies: # force update their build.gradle
  # time_machine: ^0.9.17
  path_provider: ^2.0.9
  share_plus: ^4.0.7
  file_picker: ^4.5.1 # comment all permissions in its manifest
  flutter_document_picker: ^5.1.0
  format: ^1.1.1
  jiffy: ^5.0.0
  shared_preferences: ^2.0.15

flutter:
  uses-material-design: true
  fonts:
    - family: Quattrocento
      fonts:
        - asset: assets/font/quattrocento_regular.ttf
          weight: 400
        - asset: assets/font/quattrocento_bold.ttf
          weight: 800
    - family: MorrisRoman
      fonts:
        - asset: assets/font/morris_roman_black.ttf
