name: fortuna
description: "An application of the Hedonist philosophy."
publish_to: 'none'
version: 3.6.5
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies: # force update their build.gradle
  flutter_lints: ^4.0.0
  # time_machine: ^X.X.X
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  file_picker: ^6.1.1 # comment all permissions in its manifest
  flutter_document_picker: ^5.2.3
  format: ^1.4.0
  jiffy: ^6.2.1
  shared_preferences: ^2.2.2
  vibration: ^1.8.4

flutter:
  uses-material-design: true
  fonts:
    - family: Quattrocento
      fonts:
        - asset: assets/font/quattrocento_regular.ttf
          weight: 400
        - asset: assets/font/quattrocento_bold.ttf
          weight: 800
    - family: MorrisRoman
      fonts:
        - asset: assets/font/morris_roman_black.ttf
